### ISSUE TITLE
"NorESM_LandSites_Platform" folder in the container can not do git push properly!

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#101]
I've made some changes in "NorESM_LandSites_Platform" folder in the container. I wanted to push the changes to remote git repo. But I got the following errors, even though I had username and password correct. 
```
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/huitang-earth/NorESM_LandSites_Platform.git/'
```

`git config --list` reveal an aditional line:

> http.https://github.com/.extraheader=AUTHORIZATION: basic \<token\>

I removed this line in "NorESM_LandSites_Platform/.git/config", then `git push` works.

@ka7eh Should the git configuration for ".extraheader=AUTHORIZATION" be removed for "NorESM_LandSites_Platform" folder in the container? If we do this, will there be any security issues?

**Comment by ka7eh** [comment]
Is `extraheader` config mentioned something in the repo? I don't see any reference to it.

As for the push issue part, it totally depends on your local setup. My best guess is that at some point you created a token on Github and used it for authentication and now it's expired. I assume on the first try git didn't ask you for credentials, correct?
After removing it, did you manage to authenticate with your username and pass?

**Comment by huitang-earth** [comment]
`NorESM_LandSites_Platform` folder pre-exist when we pull the image using `docker pull`

It has nothing to do with my setting. If I create a new platform folder in the container, e.g., `NorESM_LandSites_Platform_test`. Then, `git push or pull` work properly in the container. It does not have configuration of  `extraheader` .

**Comment by ka7eh** [comment]
I see what you mean. I pulled the image and saw the same thing.

I'm not sure how that's happened. It's possible it was caused by this line, which copies everything into the image, including the `.git` folder: https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/docker/Dockerfile#L16.

As you said, that line shouldn't be there. Now I'm actually thinking of removing this image and start retiring this repo.

I think most things related to running a case in a docker container is now covered in https://github.com/NorESMhub/ctsm-api. So let's use that repo instead.
