### ISSUE TITLE
With no support of openstack (e.g., on windows), how to create a virtual machine on NREC from scratch to run the platform?

### ISSUE THREAD

**Issue by huitang-earth** [NorESMhub/NorESM_LandSites_Platform#45]
Perhaps, we should have a more detailed documentation as  @evalieungh build her own NREC virtual machine for the platform? Perhaps, a screen record of all the steps to go through might be a good idea.

**Comment by evalieungh** [comment]
NREC has a good guide for this, but first it's useful to know that you need access to our project, and then navigate to the correct project and region (uio-geo-noresm-siteplatform, bgo) before using the 'Launch instance' button:
![image](https://user-images.githubusercontent.com/39821980/134153098-d2be5b68-5069-40cd-9531-254331af2507.png)

But what 'source' and 'flavor' should we use? 

The rest is handled by this tutorial:
[https://docs.nrec.no/create-virtual-machine.html ](https://docs.nrec.no/create-virtual-machine.html )

**Comment by emiliano-gelati** [comment]
Source and flavor are given in the [bash script to create a VM based on our  latest snapshot](https://github.com/NorESMhub/NorESM_LandSites_Platform/blob/platform_dev/.machine/NREC_VM_setup/create_VM_latest_image.sh):
- the "image" environment variable contains the "source" name
- "machine_size" is the "flavor"
- and so on for the other required parameters

**Comment by evalieungh** [comment]
Aha. I was confused by the standard option named 'image' not being the correct option for getting our platform image! In the Source tab, I had to use the dropdown menu to get the other option than 'image' to find our platform snapshots. 

I have set up my VM, but I think I messed up something with the SSH key because I still can't connect to it using 
`ssh centos@158.39.77.202`

I get this error message: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

Maybe something to do with MobaXterm looking in the wrong folder for the key. But I don't know how to fix it! Might looka at it again tonight.

**Comment by evalieungh** [comment]
Update: With help from @huitang-earth the SSH key problem was resolved. But, for a different purpose I realised a better solution may have been available all along. My mistake was to not open the shell in adminstrator mode, which would enable installing the linux subsystem and get Ubuntu up an running. Closing this issue for now.
