### ISSUE TITLE
README vs About page in our documentation

### ISSUE THREAD

**Issue by evalieungh** [NorESMhub/NorESM_LandSites_Platform#61]
In the documentation branch I'm working on, there is one file for the technical documentation and an additional file that makes an 'About' tab in the site. 
Would it be a good idea to make the About page and the repository README file identical? Then we would have 2 files to maintain instead of three, and avoid overlapping information.
Is there an easy way to copy/link and rename the readme.md into docs/about.md without having to manually copy the file over when the readme is updated?

**Comment by emiliano-gelati** [comment]
You can try to create `docs/about.md` as a symbolic link of `readme.md`. However, I think you should use a relative path and not an absolute path, because a user may clone the repository to a different location in the file system and then the link created with the absolute path will not work.

Example:
Folder structure:
test/
├── file.txt
├── folder
└── sub

To create a symbolic link to `file.txt` inside `sub` using a relative path:
`cd test/sub`
`ln -s ../file.txt link.txt`

Then you can move the whole folder `test` around and the link will still work, i.e. `cat link.txt` will print the content of `file.txt`.

If you instead created the link using absolute paths (`ln -s /home/user/test/file.txt /home/user/test/sub/link.txt`), moving the folder `test` to another location will break the reference.

Hopefully this works well with git

**Comment by evalieungh** [comment]
It worked! Thank you, @emiliano-gelati. The page is now up [here](https://noresmhub.github.io/NorESM_LandSites_Platform/about/ )
The logos are missing because of path issues, but that should be easy to fix.
