### ISSUE TITLE
Model configuration via settings file - output frequency and history fields

### ISSUE THREAD

**Issue by lasseke** [NorESMhub/NorESM_LandSites_Platform#93]
I am currently digging into the CLM parameter documentation to implement the adjustable options we plan to include in the settings files. IMO, two important settings are the output frequency and the variables (history fields) the model produces. These could be used to manage the potentially large file sizes of the output. [In this presentation](https://chess.w.uib.no/files/2017/10/Fan_CLM-site-simulation-practice-guide.pdf) and other places, I found that these settings can be specified via the user name list:

```
In "user_nl_clm":
 
hist_fincl2 = 'GPP', 'NEE', 'NPP', 'TOTPFTC', 'TOTVEGC', 'TOTCOLC', 'TOTLITC', 'LEAFC', 'LIVESTEMC', 'DEADSTEMC', 'FROOTC', 'TLAI', 'FSH', 'EFLX_LH_TOT', 'FSA', 'FSR', 'QFLX_EVAP_TOT', 'FPSN', 'ALBD'
hist_fincl3 = 'GPP', 'NEE', 'NPP', 'TLAI', 'FSH', 'EFLX_LH_TOT', 'FSA', 'FSR', 'QFLX_EVAP_TOT', 'FPSN', 'ALBD'
 
hist_nhtfrq = 0, -24, 1
hist_mfilt = 12, 365, 17520 "
 
#Options hist_nhtfrq, hist_mfilt decide the frequency and length of model output, 
e.g. 0 and 12 indicate monthly output, -24 and 365 indicate yearly output with daily 
mean value, 1 and 17520 indicate yearly output with per time step (30min) value
```
My suggestion would be to implement "daily", "monthly", and "yearly" output. Do I understand correctly that the three values specified for "hist_nhtfrq" can also be used individually and giving more than one value means output for all timesteps will be generated? Is it necessary to also specify "hist_mfilt" or is it okay/possible to just use a default?

Moreover, when specifying desired output variables, what exactly is the meaning of the trailing integers in the "hist_fincl2" and "hist_fincl3" variables? Can this be simplified somehow?

@huitang-earth

**Comment by evalieungh** [comment]
there is something about it here, but haven't understood it yet and a couple of links are broken: 
<https://escomp.github.io/ctsm-docs/versions/release-clm5.0/html/users_guide/setting-up-and-running-a-case/customizing-the-clm-namelist.html?highlight=hist_fincl>

**Comment by huitang-earth** [comment]
@lasseke:

default output without changing anything in “user_clm_nl”: you will get **monthly output for hundreds of variables**, each month is a file, it has **h0** in the output filename

usually the default option is enough for teaching purpose

daily output or hourly output: you need to keep such output in a separate file,  so that you will not mess up the default monthly output. Therefore, you need “hist_fincl(2-6)”，“hist_nhtfrq“ and “hist_mfilt” to define new output file. **These 3 parameters should be used together to clear define the behavior of new output**

‘hist_fincl1’ is for default output (h0). So, **never touch it without a good reason**

‘hist_fincl2’ will correspond to output that have “h1” in its name

hist_fincl3 -> “h2”, ….. and so on

no other specific meaning of the number 2 and 3 in ‘hist_fincl’

The first value in “hist_nhtfrq“ and “hist_mfilt”  is always related to the default output (h0), so keep it as monthly output, each file have only 1 month.

I prefer using ‘1’ for “hist_mfilt” for monthly or daily output, but 24 for 1-hourly output so one file include output for 1 day.

**Comment by huitang-earth** [comment]
number of values in “hist_nhtfrq“ and “hist_mfilt” should correspond to the number of ‘hist_fincl’ used, including the default output ‘hist_fincl1’ . New additional output always starts from  ‘hist_fincl2’. If you have  ‘hist_fincl2’ and  ‘hist_fincl3’,  there should be 3 values in “hist_nhtfrq“ and “hist_mfilt”

**Comment by evalieungh** [comment]
A solution for customising this has been included in the GUI already, but is lacking documentation both in helper text and in the main docs page.
